FLIR/conservator-cli

FLIR/conservator/cli/cvc.py
FLIR/conservator/local_dataset.py

Closes #165 (in clone, pulls until index.json exists with timeout and max_retries)
This also refactored LocalDataset and the inner workings of how CVC gets a LocalDataset instance. 
Basically, InvalidLocalDatasetPath is now raised by LocalDataset constructor, rather than in a hacky way within CVC to validate paths for certain commands. Tested basic commands and they still work.
Note: we can get rid of this check in DTK the next time CLI dependency version is updated

Wait for index.json, raise RuntimeException if never committed

---

docs/usage/installation.rst

Remove private repo note, and update install URLs

---

FLIR/conservator/local_dataset.py

Closes #173 
Results of `cvc download` now outputs this information:
```
INFO:FLIR.conservator.local_dataset:Total frames: 6922
INFO:FLIR.conservator.local_dataset:  Unique hashes: 6900
INFO:FLIR.conservator.local_dataset:  Cache hits: 6900
INFO:FLIR.conservator.local_dataset:Downloads attempted: 0
INFO:FLIR.conservator.local_dataset:  Reported 0 successes.
INFO:FLIR.conservator.local_dataset:  Successful downloads: 0
INFO:FLIR.conservator.local_dataset:  Failed downloads: 0
INFO:FLIR.conservator.local_dataset:Linked 6922 files.
```
Closes #174 
Empty files are now reported as errors, and do not count as cache hits (so downloading is retried if run again)

Remove empty files and improve statistics of cvc download

---

requirements.txt
setup.py

Make sure wheel is installed before installing other requirements

Add wheel as a setup requirement

---

FLIR/conservator/cli/cvc.py
FLIR/conservator/local_dataset.py
FLIR/conservator/wrappers/image.py
FLIR/conservator/wrappers/media.py
FLIR/conservator/wrappers/video.py

fix couple bugs from recent merges (oops).

Fix md5 bug

---

FLIR/conservator/config.py

This is the first part of #164 
Future PR will add support for named configs, and switching/listing/setting/deleting them

Change where configs are stored, and move old configs

---

FLIR/conservator/connection.py
FLIR/conservator/fields_manager.py

Closes #194 
See linked issue for context/justification

Stop excluding and retrying queries with problematic fields

---

FLIR/conservator/cli/managers.py

Display all media files found inside a Conservator collection, with
optional recursion.

Add CLI subcommand list-media for collections

---

docs/usage/cvc_guide.rst

Update Global Config docs to new config commands

---

FLIR/conservator/generated/schema.py

Important feature is pagination on dataset video stats to be used in move_media Tools script.
We should consider adding a test that regenerates the schema and verifies nothing changed

Update schema.py to latest

---

jenkins-pipelines/linux_desktop_build.groovy
test/Dockerfile
test/test_connection.py

For context, see: https://jiracommercial.flir.com/browse/CON-1298

Run unit tests in python:3.8 docker

---

jenkins-pipelines/linux_desktop_build.groovy
test/Dockerfile

Conservator container doesn't have git credentials... can't push

Push docs from within docker

---

FLIR/conservator/config.py
test/integration/conftest.py
test/integration/test_cvc.py
test/integration/test_projects.py

Also adds a `cvc clone` test, providing some utilities for testing  CLI commands in the future

More Project integration tests

---

FLIR/conservator/config.py
jenkins-pipelines/linux_desktop_build.groovy
test/Dockerfile
test/integration/conftest.py
test/integration/kind.yaml
test/integration/test_cvc.py
test/integration/test_projects.py

Current drawbacks to be addressed in next few PRs: 
- image tag is hardcoded
- configuration yaml is static, probably will use Jenkins artifact system to copy it from `main` fc

Jenkins run integration tests via kind

---

FLIR/conservator/managers/__init__.py
FLIR/conservator/wrappers/collection.py
FLIR/conservator/wrappers/project.py
test/integration/test_collections.py
test/integration/test_projects.py

Missing tests for methods related to media. Will add once media uploaded/download is working

Add tests for collections

---

FLIR/conservator/cli/managers.py
FLIR/conservator/conservator.py
FLIR/conservator/fields_manager.py
FLIR/conservator/file_transfers.py
FLIR/conservator/local_dataset.py
FLIR/conservator/managers/__init__.py
FLIR/conservator/managers/media.py
FLIR/conservator/util.py
FLIR/conservator/wrappers/collection.py
FLIR/conservator/wrappers/dataset.py
FLIR/conservator/wrappers/file_locker.py
FLIR/conservator/wrappers/frame.py
FLIR/conservator/wrappers/media.py
FLIR/conservator/wrappers/metadata.py
docs/api.rst
examples/download_videos.py
jenkins-pipelines/linux_desktop_build.groovy
test/data/mp4/adas_thermal.mp4
test/data/mp4/courtyard_thermal.mp4
test/data/mp4/tower_gimbal.mp4
test/integration/conftest.py
test/integration/test_download_media.py
test/integration/test_upload_media.py

Somewhat complicated refactor, I still need to test changes.

Refactor upload and download to use full URL

---

FLIR/conservator/wrappers/frame.py
test/integration/test_frame.py

Also fixed `Frame.download()`, which was failing before

Add tests for Frame operations

---

test/integration/conftest.py
test/integration/test_cvc.py

Python 3.6 does not have 'text' parameter in subprocess module

Minor changes to support python 3.6 in test code

---

test/README.md

Update tests README

---

FLIR/conservator/wrappers/dataset.py
test/integration/test_dataset.py

There are a few tests missing, related to methods for exploring/downloading commits and blobs via API. I don't think these methods are used much though... I will add tests for them if something ever breaks, or I find an abundance of free time

Test most dataset operations

---

FLIR/conservator/wrappers/dataset_frame.py
test/integration/test_dataset_frame.py

Add a wrapper for updateDatasetQaStatusNote API mutation.

Add DatasetFrame method update_qa_status_note()

---

FLIR/conservator/cli/cvc.py
FLIR/conservator/fields_request.py
FLIR/conservator/local_dataset.py
docs/usage/cvc_guide.rst

Added workout for clone timeout to CVC guide.
New sphinx version complaining about something--fixed.
Moved where process_count is checked.

Document download-index, minor cleanup

---

RELEASING.md

We will go through this tomorrow to make sure it works/has all required info.

Add RELEASING.md documenting the release process

---

FLIR/conservator/cli/interactive.py
FLIR/conservator/fields_manager.py
FLIR/conservator/generated/schema.py
FLIR/conservator/wrappers/media.py

Pending https://github.com/FLIR/flirconservator/pull/2189 (tests will fail until that is in `:prod`)
This is a breaking change, should be released as `1.3.0`

Rename assetType to spectrum

---

docs/usage/installation.rst
examples/upload_video.py

Successfully tested upload example on local Conservator install.
Also added documentation on configs.

Updated upload video example

---

FLIR/conservator/cli/managers.py
FLIR/conservator/generated/schema.py
FLIR/conservator/wrappers/media.py
test/integration/test_collections.py

Mark uploaded videos as "new"
Needed schema update to get newUpload parameter.
Also fixed upload of single media files, which has been broken from releases 1.2.0 through 1.3.0

Mark uploaded videos as "new"

---

jenkins-pipelines/linux_desktop_build.groovy

In order to unblock PR merges, the integration test stage has been
commented out until local flirconservator instances can be created
automatically again.

Jenkins pipeline: Comment out integration testing temporarily

---

docs/usage/installation.rst

Thanks to @flitchp for the fresh-install tip
This is in regards to #281

Update install doc to mention potential missing path

---

FLIR/conservator/generated/schema.py
FLIR/conservator/wrappers/collection.py
test/integration/test_collections.py

Implement 'move' method for Collection
Use new moveCollection mutation to provide a method that moves a collection into another collection
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2441k)]

Con 2464 20220322 move collection

---

jenkins-pipelines/linux_desktop_build.groovy

Normally it's best to use the configs packaged up in the fc image, so that they get updated in sync with the server code. Leave the workaround from when prod image had bad configs still there but disabled, in case there is another time when it becomes needed. (Jenkins job could set a `KIND_GIT_HASH` parameter to activate the workaround for a build)

jenkins: disable workaround for bad cluster configs

---

FLIR/conservator/generated/schema.py

requestChangesDatasetAnnotation mutation now needs dataset id

update schema to get new arg for requestChangesDatasetAnnotation

---

test/Dockerfile
test/README.md
test/integration/conftest.py

Added checks in `test/conftest.py` to ensure `git-lfs` is configured correctly, and that `conservator-mongo` is a resolvable host; added required packages to test docker container definition; updated docs.
`test/Dockerfile`
- Added required OS packages `git-lfs` and `file`
`test/README.md`
- Added test requirements
`test/integration/conftest.py`
- Added checks to ensure `git-lfs` is installed and `conservator-mongo` is resolvable
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2824)]

Con 2824 20220826 preflight checks

---

jenkins-pipelines/visgence_linux_desktop_build.groovy
test/Dockerfile

This PR adds a new groovy pipeline file for Visgence.
**New File**
`jenkins-pipelines/visgence_linux_desktop_build.groovy`
- new file without deploying docs & publish to pypi
[[Jira Task](https://jiracommercial.flir.com/browse/CON-3257)]

CON 3257 add Visgence Jenkins CLI groovy file

---

jenkins-pipelines/visgence_linux_desktop_build.groovy

This PR updates the jenkins pipeline script to have a timeout for failing/hung branches.
`jenkins-pipelines/visgence_linux_desktop_build.groovy`
- added 45 minute timeout and discard options
- merged changes from other pipeline file
- added -v flag to pytest to better define failing test
[[Jira task](https://jiracommercial.flir.com/browse/CON-3436)]

CON 3436 update Jenkins Pipeline

---

jenkins-pipelines/visgence_linux_desktop_build.groovy

This PR adds a trigger for pipeline files. Initial attempt for testing Jenkins.
`jenkins-pipelines/visgence_linux_desktop_build.groovy`
- added trigger line
[[Jira Task](https://jiracommercial.flir.com/browse/CON-3421)]

jenkins testing - WIP

---

jenkins-pipelines/visgence_linux_desktop_build.groovy

This PR is attempting to get pipeline jobs to trigger on pull requests being opened or changed.
`jenkins-pipelines/visgence_linux_desktop_build.groovy`
- added properties() wrapper
[[Jira Task](https://jiracommercial.flir.com/browse/CON-3421)]

CON 3421 jenkins pipeline update

---

jenkins-pipelines/Jenkinsfile

Brief description of the issue. 
`path/to/file.py`
- Details of what has changed in each file
- In bullet point form
[[JIRA Task](http://link_to_jira_task)]

added jenkinsfile

---

jenkins-pipelines/Jenkinsfile_integration_testing

Brief description of the issue. 
`path/to/file.py`
- Details of what has changed in each file
- In bullet point form
[[JIRA Task](http://link_to_jira_task)]

added file for integration testing

---

jenkins-pipelines/Jenkinsfile

Brief description of the issue. 
`path/to/file.py`
- Details of what has changed in each file
- In bullet point form
[[JIRA Task](http://link_to_jira_task)]

jenkinsfile modify

---

FLIR/conservator/generated/generate.sh

Sed command isnt working well on Macos
Added condition to check weather its mac and use gsed which works like linux sed
`/Users/sweiss/Documents/code/FLIR/conservator-cli/FLIR/conservator/generated`
[[JIRA Task][(http://link_to_jira_task)](https://jiracommercial.flir.com/browse/CON-3560)]

fixed for MacOS

---

test/Dockerfile

Brief description of the issue. 
`test/Dockerfile`
- Installing kubectl on docker container - fixed
[[JIRA Task](http://link_to_jira_task)]

install kubectl fix
