FLIR/conservator-cli

- FLIR/conservator/cli/managers.py
- FLIR/conservator/conservator.py
- FLIR/conservator/local_dataset.py
- FLIR/conservator/managers/__init__.py
- FLIR/conservator/managers/media.py
- FLIR/conservator/managers/searchable.py
- FLIR/conservator/managers/type_manager.py
- FLIR/conservator/util.py
- FLIR/conservator/wrappers/collection.py
- FLIR/conservator/wrappers/image.py
- FLIR/conservator/wrappers/media.py
- FLIR/conservator/wrappers/video.py
- examples/upload_many_videos.py
The new --resume-media option will first check whether a file queued up
to be uploaded has previously been uploaded to Conservator in the 
destination folder (files of the same name but different folders are 
ignored).
* If there is an incomplete upload at the destination path,
that invalid partial file will be deleted from Conservator
before new upload attempt
* If there is a complete file at the destination path but it has 
different md5sum than the local copy, that media file will be
removed from the destination folder to avoid 2 files of same name
in folder (but will not be altogether deleted from Conservator)
* If there is a complete file at the destination path that matches
the md5sum of the local copy, upload of that file can be skipped
> Upload resume

- FLIR/conservator/wrappers/collection.py
The goal here is to have consistent behavior for uploads and downloads,
to enable convenient round-trip syncs between a local folder and a
remote one:
conservator collections download /Some/Remote/Folder ~/workdir
conservator collections upload /Some/Remote/Folder ~/workdir
> Symmetric up down

- FLIR/conservator/cli/managers.py
- FLIR/conservator/configs/download.json
- FLIR/conservator/configs/upload.json
- FLIR/conservator/run_tasks_plugins/conservator_cli.py
- setup.py
conservator_cli allows directly calling CLI commands from an app instead
of using python subprocess to execute them as a child process. This
method allows CLI commands to return objects that would be further
operated in by the parent app, rather than ugly hacks where the parent
tries to reconstruct an object by parsing stdout from conservator tool
running as a subprocess.
The actual parent app that conservator_cli was tested with lives in
another (non-public) repo, but this includes a couple of example configs
that give the idea of how conservator_cli() would be called from a
parent app (see "task_config" sections).
> conservator_cli plugin for running CLI commands from another app

- FLIR/conservator/index_schema.json
Tested on a local index.json. 
`"qaStatus": null` is now `valid`.
Requested in https://jiracommercial.flir.com/browse/CON-1210
> Allow null qaStatus in index.json

- FLIR/conservator/connection.py
- FLIR/conservator/managers/searchable.py
- FLIR/conservator/paginated_query.py
- FLIR/conservator/util.py
- FLIR/conservator/wrappers/collection.py
- FLIR/conservator/wrappers/dataset.py
- FLIR/conservator/wrappers/dataset_frame.py
- FLIR/conservator/wrappers/media.py
- FLIR/conservator/wrappers/metadata.py
- FLIR/conservator/wrappers/project.py
- FLIR/conservator/wrappers/queryable.py
- FLIR/conservator/wrappers/type_proxy.py
- FLIR/conservator/wrappers/video.py
- examples/download_associated.py
- examples/download_videos.py
- examples/list_projects.py
- examples/populate_dataset.py
- examples/query_by_exact_name.py
- examples/upload_associated.py
- examples/upload_metadata.py
Closes #184 
This is a big one... In summary, everything a user touches should now be a `TypeProxy` or a scalar (`int`, `str`, `bool`, etc.)---no more access to SGQLC types.
**This can break scripts that touch private/low level attributes on previously unwrapped types.** But it is a necessary change to let us easily introduce new `TypeProxy`s in the future, and make it easier for users to work with queries. I also doubt such access is done anywhere outside of core CLI.
Previously, SGQLC instances were only turned into a TypeProxy if there was a known subclass with a matching type. That meant non-wrapped types didn't have the TypeProxy methods (like `to_json`). With this change, **all** unknown (and non-scalar) types are wrapped with a generic instance of `TypeProxy`.
This applies in two …
> Hide SGQLC types from users with generic TypeProxy

- FLIR/conservator/local_dataset.py
- FLIR/conservator/util.py
Closes #181 
The md5 of a file in the cache is verified when checking that it exists. This does make `cvc download` resume take noticeably longer, but is probably worth it.
A try/except was added to `download_file`. If interrupted, deletes the file. I tested a few times, and this seems to have solved empty files being left behind after a Control-C mid-download.
> Remove file if download is interrupted, check cache md5

- FLIR/conservator/local_dataset.py
Frames were being downloaded out of order because we used a `set` of hashes (unordered). Now we use a `OrderedDict`
Old CVC would link as files were downloaded. Now we do the same. This involved quite a bit of refactoring because of our reduction to unique hashes.
> Download frames in order they appear

- FLIR/conservator/local_dataset.py
Links should only be created if `src` exists.
> Don't link if download fails

- FLIR/conservator/connection.py
- FLIR/conservator/paginated_query.py
- FLIR/conservator/wrappers/collection.py
- FLIR/conservator/wrappers/dataset.py
- FLIR/conservator/wrappers/dataset_frame.py
- FLIR/conservator/wrappers/file_locker.py
- FLIR/conservator/wrappers/frame.py
- FLIR/conservator/wrappers/media.py
- FLIR/conservator/wrappers/metadata.py
- FLIR/conservator/wrappers/project.py
Closes #193 
Not needed--base can be gotten from query.container
The kwarg is still added to the method signature, just ignored. This won't affect any scripts that do provide it
> Stop using operation_base in query

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/config.py
- FLIR/conservator/config.py
- docs/usage/installation.rst
Closes #164 
```
Usage: conservator config [OPTIONS] COMMAND [ARGS]...
Manage configs
Options:
--help  Show this message and exit.
Commands:
create       Create a config
delete       Delete config
edit         Edit config
list         List available config names
set-default  Set default config
view         View config
```
> Add support for named configs, improve config management

- FLIR/conservator/wrappers/collection.py
If a project doesn't exist, create_from_remote_path() would produce a bad
GraphQL query with a '/' in front of the project name.  Generally, new
projects won't need to be created, but test code will be likely to be
creating new projects on a local development Conservator server, so it
helps if this works correctly.
> Fix project name error when creating a new remote collection path

- FLIR/conservator/managers/media.py
- FLIR/conservator/wrappers/image.py
- FLIR/conservator/wrappers/media.py
- FLIR/conservator/wrappers/video.py
Closes #186 
Get fromo ID not useful: `Frame.from_id(id)` and `Frame.populate(fields)` already exist
Get frame by index already exists for `Video`, moved to `MediaType`.
Added `Image.get_frame`
> Move get_frame methods to MediaType

- FLIR/conservator/cli/managers.py
Create a new path via the command line.  Add the --recursive option to
create all missing path components, otherwise a missing base path will
be considered an error.
> Add 'create-path' command for collections

- FLIR/conservator/local_dataset.py
- FLIR/conservator/util.py
This was briefly discussed in slack. 
This makes it much more clear what's going on, and how much time is left for everything to be downloaded. I changed some of the status reporting, and added a reminder about the `-p` option. I encountered an connection error, so added an exception handler to make sure it's caught and the download continues.
Tested with a 3k image dataset, seemed to work great.
> Use a single progress bar for cvc download

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/cvc.py
- FLIR/conservator/cli/interactive.py
- FLIR/conservator/cli/managers.py
- FLIR/conservator/conservator.py
Support specifying non-default Conservator config by name in CLI commands
Useful for advanced users and developers who have access to more than one FLIR Conservator account (either different users or different servers)
conservator --config prod collections download --media --recursive /AndresTest ./AndresTest
conservator --config staging collections upload -c --media --recursive /AndresTest ./AndresTest
cvc --config priv_user clone super-test-dset
> Config as option

- test/integration/conftest.py
When running off of docker (not using kind), the mongodb box's IP was hardcoded.
Now it is fetched with the `docker inspect` command. This only affects local dev deployment using docker (from run-webapp.sh, run-workers.sh, etc.)
**This PR is branched from `kube-integration`. Review that first!**
> Use docker inspect to find IP of mongo

- FLIR/conservator/managers/__init__.py
When a metadata file had a media id that couldn't be found in Conservator,
the upload method was printing an error message but then tried to
upload the metadata anyways, causing an exception that aborts
the rest of the collection upload
File "conservator-cli/FLIR/conservator/managers/__init__.py",
line 147, in upload
media.upload_metadata(file_path)
AttributeError: 'bool' object has no attribute 'upload_metadata
Only attempt the metadata upload if its corresponding media could
actually be found.
> collections upload: don't throw exception on metadata with missing media

- jenkins-pipelines/linux_desktop_build.groovy
Docs deploy failing on `main`. I think Jenkins pulls LFS in a weird way. Throwing in a `git reset --hard` before `git checkout gh_pages` should fix it...
> Fix Jenkins pipeline docs deploy after adding LFS

- FLIR/conservator/index_schema.json
Fields stay optional unless they get added to the "required" list
for the corresponding object. So, don't list these.
> Update dataset validation schema with new optional fields

- requirements.txt
- setup.py
Turns out dataclasses module was added in python 3.7, so fix the list
of dependencies by adding the external backport module for python 3.6
> backfill dataclasses module for python 3.6

- requirements.txt
- setup.py
With click 6.x, both 'conservator' and 'cvc' tools error out with
TypeError: main() got an unexpected keyword argument 'log_level'
> specify minimum click dependency version as 7.x

- jenkins-pipelines/linux_desktop_build.groovy
- test/Dockerfile
- test/integration/conftest.py
Having jenkins run docker with '--init' is supposed to tell docker to clean up child processes after the temporary container created for testing is stopped. This should prevent accumulation of zombie processes inside the jenkins slave container.
> Jenkins cleanup

- test/integration/test_media.py
All examples are covered except for upload_many and upload_metadata. The second will be covered in a later test. This adds the first to media tests.
> Ensure tests cover all examples

- FLIR/conservator/wrappers/file_locker.py
- test/data/txt/lorem.txt
- test/integration/test_file_locker.py
Runs same tests for media, dataset, collection
Tests are pretty simple, and work off of each other (not best practice, D: )
> Add tests for FileLockerType

- FLIR/conservator/wrappers/dataset.py
- FLIR/conservator/wrappers/metadata.py
- test/integration/test_metadata.py
Dataset metadata tests FAIL because the import-dataset-metadata worker is not deployed in a k8s instance. Will ask evan about this. 
Until changed, this test case is skipped.
> Add tests for MetadataType

- jenkins-pipelines/linux_desktop_build.groovy
- version.py
To release:
```
git checkout main
git tag -a [version] -m "Release [version]"
git push origin [version]
```
Go to jenkins:
- find the new version under the `Tags` tab.
- click `Build`. this runs tests, builds, and pushes to pypi
Verify version is released on [pypi page](https://pypi.org/project/conservator-cli/), and try `pip install conservator-cli` from a new `venv`.
**Note:** 
- Version string must follow [PEP 440](https://www.python.org/dev/peps/pep-0440/). For instance: `1.1.1`, `1.2.34`
- Version tag must be annotation (created with `-a`).
- Tag must be on `main` branch.
> Jenkins release on PyPI

- docs/usage/installation.rst
Removing `requirements.txt` section because we now use standard pypi, so it's nothing special.
> Update installation instructions to use PyPI

- test/integration/test_cli.py
I'm not going to add any integration tests for CLI commands at this time. If something breaks, a bug is found, or we make changes to any commands, we should add tests.
This PR just adds a file/template for CLI tests in the future
> Add a basic CLI test as a template for future tests

- test/integration/test_dataset.py
Should fix failing tests. There's a race condition in how quickly the dataset commit worker does its thing
Will find a better solution if this fails again in the future
> Increase delays in Dataset commit integration test

- FLIR/conservator/cli/managers.py
- FLIR/conservator/wrappers/collection.py
Add new `--preview_videos` option to `conservator collection download` to download preview videos in place of full videos.
> Add option to download preview videos from a collection

- FLIR/conservator/wrappers/file_locker.py
- test/integration/test_file_locker.py
With  https://github.com/FLIR/flirconservator/pull/2187/ , FileLocker will never be null
This PR updates tests and removes a `None` check.
Of course, this PR will fail to pass tests until that PR reaches `:prod`.
> Adjust tests for fixed FileLocker

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/cvc.py
- FLIR/conservator/cli/interactive.py
- FLIR/conservator/cli/managers.py
This fixes some issues when running commands without a valid config (such when creating your first config).
Conservator will only be created from config_name (or `default`) when it will be needed.
In short, click ctx now holds config_name, not conservator instance.
> Avoid creating Conservator until needed in Click context

- setup.py
This should work better(?). Will test locally, and again once deployed to PyPI
> Use environment marker for pyreadline

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/cvc.py
When attempting to detect the package version, click's version_option()
code was hitting an exception:
RuntimeError: 'FLIR' is not installed. Try passing 'package_name' instead.
Pass `package_name` as suggested.
> Fix exception raised from conservator --version

- requirements.txt
- setup.py
Pretty simple fix to ensure that click is at least version 8.0.0  
tested it to make sure that error does not show up anymore after ensuring click is at least 8.0.0  
Link to jira ticket: https://jiracommercial.flir.com/browse/CON-1686
> set requirements to ensure click >= 8.0.0

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/cvc.py
- docs/usage/cli_quickstart.rst
Back in 1.2.1 release, if '--config' option was not supplied then
config_name would be left as None, triggering Conservator.create() to
use Config.default() which searches the environment before looking
for a config file named default.json
Commit 5b0edfda39 changed the default value for config_name to "default"
instead of None, so calling the tools *without* "--config" (which should
get the special treatment) and "--config default" (just look for a config
file named default.json) could no longer be distinguished.
Switch back to calling commands without --config argument sets
config_name=None which thus takes the special Config.default() path
in Conservator.create()
> Restore ability of conservator utils to use config from env

- FLIR/conservator/cli/cvc.py
- FLIR/conservator/local_dataset.py
Even with HTTP 502 retries, occasionally frames fail to download into
the cache.  Re-queue failed frame downloads and retry them up to the
configured retry limit.
If frames are missing after hitting the retry limit, exit cvc download
with a non-zero exit code to indicate failures.
> cvc download: Retry failed dataset cache downloads

- FLIR/conservator/paginated_query.py
- FLIR/conservator/wrappers/dataset.py
- test/integration/test_dataset.py
Datasets now have 3 new methods:
* get_frames_reversed() - Reverses the get_frames() iterator in order to
find the newest frames first, which speeds up the search for new
dataset IDs that have just been added to the dataset.  Dataset frames
are always returned in same order in which they were added.
* associate_frame() - Associates a dataset frame ID with a video frame
or dataset frame ID specified in an AddAssociatedFrameInput object.
* add_frames_with_associations() - Adds new frames to a dataset, then
associates the new dataset frame IDs with other video or dataset frame
IDs using a table that maps source video frame IDs to lists of
AddAssociatedFrameInput objects.
Add new PaginatedQuery parameters `reverse` and `total_unpack_field` to
iterate through API results in reverse order.
> Add associated frame methods to dataset objects

- FLIR/conservator/generated/schema.py
- FLIR/conservator/local_dataset.py
- FLIR/conservator/wrappers/frame.py
- test/integration/test_frame.py
- test/integration/test_media.py
- test/integration/test_metadata.py
Frame.add_annotation() is now Frame.add_annotations(), and accepts a list of AnnotationCreate objects.
Update to the latest Conservator GraphQL schema.
In test_frame.py, change `test_add_annotation()` to `test_add_annotations()`.
Remove a spurious error displayed by `cvc download` if no frames need to be downloaded.
Due to the API change, when this PR is merged conservator-cli will be tagged and released as version 2.0.0.
> Support Conservator API change for creating annotations

- FLIR/conservator/wrappers/collection.py
In the Collection method `from_remote_path()`, strip off any trailing slash before sending the path to the `collectionByPath` API call.  The API call will fail and the user will not receive clear feedback about what caused the failure otherwise.
> Remove trailing slashes from collection paths

- FLIR/conservator/wrappers/dataset.py
- test/integration/conftest.py
- test/integration/test_dataset.py
Implement Dataset object method to remove frames
remove_frames() can take a list of either Frame or DatasetFrame
objects and remove the corresponding frames. There are 2 separate
mutations in the server API, one for Frame and another for DatasetFrame,
so the type of wrapper object is used to decide which mutation to use.
Addresses #280
> Support remove frames

- FLIR/conservator/generated/schema.py
- examples/dataset_annotation_qa.py
- examples/video_annotation_qa.py
Updated `schema.py` to include new APIs (specifically, those that allow QA on individual annotations). Also added some trivial code examples for use of those APIs.
**Changes:**
- Updated schema
`examples/dataset_annotation_qa.py`
`examples/video_annotation_qa.py`
- Examples for using the QA APIs on dataset/video annotations
[[JIRA Task][https://jiracommercial.flir.com/browse/CON-2394]]
> CON-2394_20220228_update-schema

- FLIR/conservator/file_transfers.py
- test/integration/test_cvc.py
test_cvc_clone_download() was waiting a fixed amount between
using dataset API to commit changes and cloning that same dataset.
The test would fail if the dataset commit took longer than
expected to complete. Instead of bumping up the sleep time,
making tests slower than needed in most cases, watch for the commit
to appear in the dataset's commit history each second up to 30 seconds.
Also add response code to FileUploadException info, which is thrown
in the case of a failed media upload attempt. For instance, now you can tell
whether the failure was 502 Bad Gateway or 413 Request Entity Too Large
> remove race codition from cvc integration tests

- FLIR/conservator/generated/schema.py
- test/README.md
Updates schema to bring in new changes from `staging` build of conservator (most `ID` fields are now `ConservatorID` types).
- Updated schema
`test/README.md`
- Added note to indicate that running integration tests will delete all data from the database being used.
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2413)]
> Con 2413 20220307 update schema

- .github/pull_request_template.md
- FLIR/conservator/generated/schema.py
- FLIR/conservator/local_dataset.py
- FLIR/conservator/util.py
- jenkins-pipelines/linux_desktop_build.groovy
- test/integration/cluster/start-cluster.sh
Updates CVC/`local_dataset` functionality to check image md5s using new bulk API.
Note that this code relies on Conservator [PR 2511](https://github.com/FLIR/flirconservator/pull/2511), which implements the `check_frames_by_md5` API.
`.github/pull_request_template.md`
- Added template for PRs
- Updated schema to bring in new `check_frames_by_md5` API
`FLIR/conservator/local_dataset.py`
- Updates code to check image md5s in groups of 100 when uploading
`FLIR/conservator/util.py`
- Added `chunks` function (see code for details)
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2400)]
> Con 2400 20220302 user bulk md5 api

- test/integration/conftest.py
minikube is another kubernetes implementation like kind,
but the service mapping rules are a little different so it
needs to be a separate case from kind, rather than just
"kubernetes or not" like before.
Added a custom option for pytest, to make selecting the server deployment
explicit rather than trying to come up with heuristics to distinguish
kind and minikube (default value is 'kind')
```
$ pytest --help
custom options:
--server-deployment={docker,kind,minikube}
Type of deployment for tested conservator instance
```
Here are the new rules for how test setup varies according
to server deployment type, with minikube added in:
* kubernetes
mongo ip = lookup with kubectl
* kind
conservator port = 8080
* pytest running in docker
conservator IP = hostIP (not localhost)
* pytest running …
> Support minikube as new deployment type for Conservator server

- FLIR/conservator/connection.py
Send user agent header to server containing following info:
conservator-cli/$CLI_VERSION Python/$PYTHON_VERSION $OS_TYPE/$OS_VERSION
Example:
POST /graphql HTTP/1.1
Accept-Encoding: identity
User-Agent: conservator-cli/2.3.0-3+g90f0f2d Python/3.6.9 Linux/4.15.0-147-generic
...
`FLIR/conservator/connection.py`
- add User-Agent string to http request headers
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2491)]
> informative user-agent header

- FLIR/conservator/fields_manager.py
- FLIR/conservator/generated/generate.sh
- FLIR/conservator/generated/schema.py
- examples/create_dataset_frames.py
- examples/paginate_video_frames.py
- requirements.txt
- setup.py
- test/README.md
- test/integration/test_media.py
Adds support for the Conservator `createDatasetFrames` API, and example code.
`examples/paginate_video_frames.py`
`FLIR/conservator/fields_manager.py`
`test/integration/test_media.py`
- Replaced deprecated `frames_count` field with `frame_count`
`FLIR/conservator/generated/generate.sh`
- Removed `--exclude-deprecated` parameter, because some tests/other code seems to depend on deprecated fields/APIs
- Updated schema with latest changes from Conservator
`examples/create_dataset_frames.py`
- Example code showing how to use the new API to create dataset frames
`test/README.md`
- Added description of previously undocumented `--server-deployment` command-line arg
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2527)]
> Con 2527 20220411 sipport create dataset frame api

- FLIR/conservator/generated/schema.py
- examples/dataset_annotation_qa.py
Updates schema.py
- Updated schema to match latest conservator release
- Removed `label` fields from DatasetAnnotation/Annotation - they are deprecated in Conservator
`examples/dataset_annotation_qa.py`
- Updated query calls to match new API signature
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2610)]
> Con 2610 20220504 update dataset annotation ap is

- FLIR/conservator/cli/cvc.py
- FLIR/conservator/local_dataset.py
- FLIR/conservator/wrappers/dataset.py
- docs/usage/cvc_guide.rst
- test/integration/test_cvc.py
* mention using `cvc publish` to create associated files in cvc guide
* mention using `cvc publish` to create associated files in `cvc add` error message, if user (unsuccessfully) attempts to use `cvc add` instead
* fix race in `cvc publish` that sometimes ended with working dir at previous commit, making a new associated file disappear from working dir until next `cvc pull` got the working dir up-to-date
> cvc: improve user experience for creating associated files

- FLIR/conservator/cli/__init__.py
- FLIR/conservator/cli/cvc.py
- FLIR/conservator/connection.py
- FLIR/conservator/generated/schema.py
- FLIR/conservator/util.py
- requirements.txt
- setup.py
- test/integration/test_collections.py
- test/integration/test_dataset.py
Adds version checking.
`conservator --version` will now also display the latest version number from PyPi
Any action that attempts to create a connection to Conservator will compare the locally installed version with the latest version from PyPi, and print an appropriate warning message if they are not the same.
`FLIR/conservator/cli/__init__.py`
- Add PyPi version to `--version` output
`FLIR/conservator/connection.py`
- Call `compare_conservator_cli_version` when someone attempts to instantiate connection
- Minor update (new `password` field in `createUser` API
`FLIR/conservator/util.py`
- Added `get_conservator_cli_version` function, which gets the latest version of the package from PyPi using `requests`
- Added …
> Con 2761 20220803 check for up to date

- FLIR/conservator/util.py
- jenkins-pipelines/linux_desktop_build.groovy
Adds cleanup steps to jenkins build process, to remove intermediate docker build images, and other docker images more than 5 days old.
`FLIR/conservator/util.py`
- Refactored `semver` usage
`jenkins-pipelines/linux_desktop_build.groovy`
- Adds commands to clean up docker images
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2811)]
> Con 2811 20220823 cleanup docker after test

- FLIR/conservator/file_transfers.py
- FLIR/conservator/util.py
Users have complained about issues using `cvc download`. This PR attempts to disgnose and fix these issues by reporting the exact status codes of failed downloads, and attempting to retry 504 errors.
`FLIR/conservator/file_transfers.py`
- Print out non-successful status codes
- Automatically retry on 504 error
- Fix some linting issues
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2819)]
> Con 2819 20220817 improve cvc download

- jenkins-pipelines/linux_desktop_build.groovy
Changes the commands that clean up docker images to only affect Conservator images.
`jenkins-pipelines/linux_desktop_build.groovy`
- Filter docker images to delete only conservator-related images
- Command is structured so that if it fails (e.g. if there are no images to delete) the entire build doesn't automatically fail
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2840)]
> Con 2840 20220831 filter docker image purge

- requirements.txt
- setup.py
Installation of Conservator-CLI was failing during Conservator build; error was:
```
Could not find a version that satisfies the requirement typing-extensions<5,>=4.2; python_version < "3.8" (from graphql-core->sgqlc>=13->conservator-cli) (from versions: 3.6.2, 3.6.2.1, 3.6.5, 3.6.6, 3.7.2, 3.7.4, 3.7.4.1, 3.7.4.2, 3.7.4.3, 3.10.0.0, 3.10.0.1, 3.10.0.2, 4.0.0, 4.0.1, 4.1.0, 4.1.1)
No matching distribution found for typing-extensions<5,>=4.2; python_version < "3.8" (from graphql-core->sgqlc>=13->conservator-cli)
The command '/bin/sh -c pip3 install conservator-cli' returned a non-zero code: 1
```
Temporary solution is to set the version of `sgqlc` to `16.0` for python < 3.7, which seems to work.
In the longer-term, we need to update the Dockerfile for Conservator to Ubuntu 20.04.
**To …
> Tweaked dependencies

- FLIR/conservator/cli/cvc.py
- FLIR/conservator/local_dataset.py
- requirements.txt
- `cvc` support for `-a`/`--include-analytics` re-added, with a note that `-a` is deprecated in favor of `-r`
- Will download raw/analytics data for `index.json` regardless of whether the field is `rawMd5` or `analyticsMd5`
- Added missing requirement to `requirements.txt` which was causing issues with document build
`FLIR/conservator/cli/cvc.py`
- Re-add `-a`/`--include-analytics` options to download command
`FLIR/conservator/local_dataset.py`
- Check both `analyticsMd5` and `rawMd5` when downloading raw TIFF data
`requirements.txt`
- Added missing requirement `myst-parser` 
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-3189)]
> Added backwards compatibility for index.json with analytics fields

- docs/usage/installation.rst
Python 3.x on OSX does not include SSL certificates necessary to connect to Conservator securely. There is a script bundled with Python that will fix the issue, and this PR adds a note to the documentation to describe it.
`docs/usage/installation.rst`
- Describes how to address OSX SSL issue
[[JIRA Task](https://jiracommercial.flir.com/browse/CON-3270)]
> Updated docs to address OSX error

- FLIR/conservator/cli/managers.py
- FLIR/conservator/wrappers/collection.py
- docs/usage/cli_quickstart.rst
Document what to expect when running the same command again after the download process is interrupted.
Add a new command-line option to allow datasets to be removed and re-downloaded.  Skip existing datasets in the target directory if the option is not present.
`FLIR/conservator/cli/managers.py`
- Add help text that appears in response to `conservator collections download --help`
- Add a new option `--overwrite-datasets` to force existing datasets in the target directory for `conservator collections download` to be removed and re-downloaded
`FLIR/conservator/wrappers/collection.py`
- Support the new `--overwrite-datasets` option for `conservator collections download`.  Existing datasets in the target directory will now be skipped if this option is not set, instead of …
> Improve help text and online documentation for collection download command and improve collection dataset handling

- jenkins-pipelines/linux_desktop_build.groovy
- test/Dockerfile
- version.py
Git refuses to work properly when run as root.  Run jenkins tasks as an unprivileged user inside the kind / kubernetes cluster instead.
`version.py`
- Display any exceptions encountered inside the `try:` block in `call_git_describe()` to make it easier to track down failures when collecting version information from git
`test/Dockerfile`
- Create an unprivileged user `tester` for use inside the docker image
- Make the `$HOME/.local/bin` directory available in $PATH, since that is where pip installs executables when not run as root
- Make the github.com SSH RSA host key available inside the docker image to work around a git error
`jenkins/linux_desktop_build.groovy`
- Run the docker image as the `tester` user, and create an `/etc/hosts` entry for conservator-mongo on the …
> Drop root privileges in Jenkins script

- test/Dockerfile
This PR updates Dockerfile with new k8s url for gpg key
`test/Dockerfile`
- updated url
[[Jira Task](https://jiracommercial.flir.com/browse/CON-3481)]
> CON 3481 update k8s gpg url in Dockerfile

- FLIR/conservator/util.py
The semver code was not working as expected. This has been fixed.
To test:
- install this branch locally (`pip install .`) and test using `conservator whoami`. The message should report an unreleased version.
- install this branch from github (`pip install git+https://github.com/FLIR/conservator-cli.git@CON-3858_20230525_fix-semver-code`) and test using `conservator whoami`. The message should report an unreleased version.
- install this branch using either method, and then edit the installed `version.py` file to give a different version that is lower than the currently released version (2.13.0). `version.py` can be found in e.g. `venv/lib/python3.x/site-packages/FLIR/conservator`.
`FLIR/conservator/util.py`
- Tweaked semver code to recognize unreleased builds, and …
> Work on version checking

- FLIR/conservator/cli/cvc.py
- FLIR/conservator/local_dataset.py
- docs/usage/cvc_guide.rst
This PR adds a message about using the -s flag when downloading with cvc.
**Files Changed**
`FLIR/conservator/local_dataset.py`
`FLIR/conservator/cli/cvc.py`
- added error handling and message
`docs/usage/cvc_guide.rst`
- updated docs
[[Jira Task](https://jiracommercial.flir.com/browse/CON-2179)]
> CON 2179 add error handling for symlink

- README.md
This PR updates the Conservator CLI README with the new Jenkins embed status.
`README.md`
- updated url
[[Jira Task](https://jiracommercial.flir.com/browse/CON-3421)]
> CON 3421 update cli readme
